# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ms_qrCodeDecoder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ms_qrCodeDecoder.proto\x12\rqrCodeDecoder\"\x1e\n\rDecodeRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\" \n\rQRCodeContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2e\n\x14QRCodeDecoderService\x12M\n\rQRCodeDecoder\x12\x1c.qrCodeDecoder.DecodeRequest\x1a\x1c.qrCodeDecoder.QRCodeContent\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ms_qrCodeDecoder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DECODEREQUEST._serialized_start=41
  _DECODEREQUEST._serialized_end=71
  _QRCODECONTENT._serialized_start=73
  _QRCODECONTENT._serialized_end=105
  _QRCODEDECODERSERVICE._serialized_start=107
  _QRCODEDECODERSERVICE._serialized_end=208
# @@protoc_insertion_point(module_scope)
